# Numpy Arrays

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


0 dimensional array

In [2]:
import numpy as np

arr1 = np.array(42)

print(arr1)

42


1-D arrays or unidimensional array

In [3]:
import numpy as np

arr2 = np.array([1, 2, 3, 4, 5])

print(arr2)

[1 2 3 4 5]


In [4]:
import numpy as np

arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr3)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


# Higher Dimension Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array Indexing

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])


2


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


Accessing 2-D arrays

In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


Negative Indexing

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[1,2,3,4,19]])

print('Last element from 2nd dim: ', arr[2, -1])

Last element from 2nd dim:  19


# Slicing in array 

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [20]:
arr[-1:-8:-1]

array([7, 6, 5, 4, 3, 2, 1])

In [14]:
arr[:4]

array([1, 2, 3, 4])

In [15]:
arr[-3:-1]

array([5, 6])

In [16]:
arr[1:5:2]

array([2, 4])

Slicing 2-D arrays

In [23]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [22]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
arr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[1,2,3,4,5]]])

#print(arr[0:2, 2])

In [51]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [54]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 1  2  3  4  5]]]


# Some Mathematical Operations on Arrays

Scalar Addition

In [20]:
import numpy as np 
arr = np.array([10, 20, 30.5, -40])
arr = arr+5
print(arr)

[ 15.   25.   35.5 -35. ]


Scalar Multiplication and Division

In [21]:
arr4 = arr*3
arr4

array([  45. ,   75. ,  106.5, -105. ])

In [22]:
arr5 = arr/5
arr5

array([ 3. ,  5. ,  7.1, -7. ])

In [23]:
arr2 = np.array([1,2,3,4])
arr3 = arr - arr2
arr3

array([ 14. ,  23. ,  32.5, -39. ])

Array Multiplication (Element-wise Multiplication) 

In [2]:
import numpy as np

a = np.array([2, 1, 1])
b = np.array([3, 1, 1])
#a * b


In [ ]:
i(1-1)-j(2-3)+k(2-3)
(0,1,-1)

Array Multiplication (Dot Product) 

Array Multiplication (Cross Product)

In [3]:
import numpy as np
np.cross(a,b)

array([ 0,  1, -1])

Exponenets and Logarithms

In [27]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

Logarithm functions can be different based on base
1. Natural Log
2. Logarithm base 2
3. Logarithm base 10

In [28]:
#Natural Log
np.log(np.e)

1.0

In [29]:
np.log(10)

2.302585092994046

In [30]:
#Logarithm base 2
np.log2(10)

3.321928094887362

In [31]:
#Logarithm base 10
np.log10(10)

1.0

# Multidimensional Arrays

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [33]:
b = np.reshape(a,(2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a = np.arange(4)
a

array([0, 1, 2, 3])

Same multiplication operations can be applied on multidimensional arrays 

Slicing Multidimensional arrays

In [35]:
a= np.reshape(np.arange(30), (5,6)) #taking 5,6 because their product will result 30

In [36]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
b= a[1:4,0:2]
b

array([[ 6,  7],
       [12, 13],
       [18, 19]])

In [38]:
d = a[:, 0] # select all elements in the 0-th column
print(d)

[ 0  6 12 18 24]


In [39]:
print(a[1])

[ 6  7  8  9 10 11]


In [40]:
b = a[:3, :3]
print(b)

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [41]:
# Access an element at row 1, column 2
print(a[1, 2]) 

8


In [42]:
# Modify an element at row 0, column 3
a[0, 3] = 20
a

array([[ 0,  1,  2, 20,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
subarr = a[0:2,1:3]

In [44]:
subarr

array([[1, 2],
       [7, 8]])

In [45]:
subarr *=2
subarr

array([[ 2,  4],
       [14, 16]])

In [46]:
np.sum(a)

470

In [47]:
np.mean(a,axis=1)

array([ 5.83333333, 11.        , 14.5       , 20.5       , 26.5       ])

# Matrix Multiplication (Dot Product)

In [24]:
import numpy as np
A = [[1, 0, 8],
    [2, 7, 9],
    [3, 6, 1]]

B = [[2, 0, 3],
    [1, 2, 4],
    [0, 2, 5]]
 

result= [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
result = np.cross(A,B)
 
for r in result:
    print(r)

[ 0 13  0]
[10  1 -3]
[ 28 -15   6]


In [25]:
res = np.dot(A,B)

for s in res:
    print(s)

[ 2 16 43]
[11 32 79]
[12 14 38]


In [28]:
np.cross(A,B)

array([[  0,  13,   0],
       [ 10,   1,  -3],
       [ 28, -15,   6]])

In [4]:
import numpy as np
x = np.arange(45).reshape(3,3,5)

In [5]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [6]:
x[1:, 0:2, 1:4]

array([[[16, 17, 18],
        [21, 22, 23]],

       [[31, 32, 33],
        [36, 37, 38]]])

# Sorting the Matrix

These two sort functions sort each row of the matrix individually

In [49]:
a = np.array([[1,4], [3,1]])
a.sort()
a

array([[1, 4],
       [1, 3]])

In [12]:
n = np.matrix('[-1, 2, 3; 4, -5, 6; 7, -8, 9]') 
           
p = n.argsort() 
     
print(p) 

[[0 1 2]
 [1 0 2]
 [1 0 2]]


When we want to sort whole matrix as in the sequemce to get the sorted elements in a list 

In [13]:
Matrix = [[1, 20, 43, 14],
          [50, 69, 17, 81],
          [99, 10, 11, 22],
          [13, 54, 95, 16]]

arr = []
x, n, m = 0, 4, 4

for i in range(n):
    for j in range(m):
        arr.append(Matrix[i][j])

size = n*m
arr.sort()

for i in range(size):
    print(arr[i], end=" ")

1 10 11 13 14 16 17 20 22 43 50 54 69 81 95 99 

In [15]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [30]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

In [31]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [32]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
r = np.random.default_rng(0)

In [37]:
r.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [40]:
r.random((5,5))

array([[0.01652764, 0.81327024, 0.91275558, 0.60663578, 0.72949656],
       [0.54362499, 0.93507242, 0.81585355, 0.0027385 , 0.85740428],
       [0.03358558, 0.72965545, 0.17565562, 0.86317892, 0.54146122],
       [0.29971189, 0.42268722, 0.02831967, 0.12428328, 0.67062441],
       [0.64718951, 0.61538511, 0.38367755, 0.99720994, 0.98083534]])

In [43]:
r.integers(5, size=(5,5))

array([[4, 0, 2, 3, 4],
       [2, 1, 1, 2, 2],
       [3, 4, 0, 4, 2],
       [1, 3, 2, 1, 1],
       [3, 2, 2, 1, 3]], dtype=int64)

In [44]:
a = np.array([1,2,2,2,3,4,5,6,6,7,8,9,1,0,3])

In [45]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
unique, indices = np.unique(a, return_index=True)

In [47]:
indices

array([13,  0,  1,  4,  5,  6,  7,  9, 10, 11], dtype=int64)

In [48]:
unique

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])